export enum ApplicationStatus {
  SENT = 'SENT',
  DENIED = 'DENIED',
  APPROVED = 'APPROVED',
  UNDER_CONSIDERATION = 'UNDER_CONSIDERATION',
  INTERMEDIATE = 'INTERMEDIATE',
  DOESNT_MEET_THE_REQUIREMENTS = 'DOESNT_MEET_THE_REQUIREMENTS'
}
