export enum Can {
  EDIT_businessObjects = 'EDIT_businessObjects',
  ADD_personGroup = 'ADD_personGroup',
  ADD_persons_to_personGroup = 'ADD_persons_to_personGroup',
  DELETE_personGroup = 'DELETE_personGroup',
  DRAG_personGroup = 'DRAG_personGroup',
  ADD_organizationNode = 'ADD_organizationNode',
  DELETE_organizationNode = 'DELETE_organizationNode',
  DRAG_organizationNode = 'DRAG_organizationNode',
  DELETE_person_from_personGroup = 'DELETE_person_from_personGroup',
  SEND_invitation = 'SEND_invitation',
  EDIT_person = 'EDIT_person',
  VIEW_PAGE_businessObjects = 'VIEW_PAGE_businessObjects',
  VIEW_PAGE_company = 'VIEW_PAGE_company',
  EDIT_isSystem_of_formField = 'EDIT_isSystem_of_formField',
  TRANSFER_bo_structure = 'TRANSFER_bo_structure',
  EDIT_menu_item = 'EDIT_menu_item',
}
