export enum UserRole {
  AUTHORIZED_CLIENT = 'AUTHORIZED_CLIENT',
  IDENTIFIED_CLIENT = 'IDENTIFIED_CLIENT',
  UNAUTHORIZED_CLIENT = 'UNAUTHORIZED_CLIENT',
  ADMIN = 'ADMIN',
  NEWS_MANAGER = 'NEWS_MANAGER',
  APPLICATION_MANAGER = 'APPLICATION_MANAGER',
  PRODUCT_MANAGER = 'PRODUCT_MANAGER',
  FO_MANAGER = 'FO_MANAGER'
}
