export enum BoNativeFieldType {
  CREATED_AT = 'CREATED_AT',
  LAST_MODIFIED_AT = 'LAST_MODIFIED_AT',
  CREATED_BY = 'CREATED_BY',
  LAST_MODIFIED_BY = 'LAST_MODIFIED_BY',
  PARTICIPANTS = 'PARTICIPANTS',
}
